service: expense-tracker-backend  

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:Query
            - dynamodb:DeleteItem
          Resource: arn:aws:dynamodb:ap-south-1:*:table/expenses-tracker-frontend-isha

functions:
  add-expense:
    handler: handler.addExpense
    events:
      - http:
          path: add-expense
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key

  get-expenses:
    handler: handler.getExpenses
    events:
      - http:
          path: get-expenses
          method: get
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key

  delete-expense:
    handler: handler.deleteExpense
    events:
      - http:
          path: delete-expense
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key

plugins:
  - serverless-offline

package:
  individually: true
